# Generated by Django 5.1.5 on 2025-08-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_order_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '未完了'), ('completed', '完了'), ('canceled', 'キャンセル')], default='pending', max_length=20),
        ),
    ]
