# Generated by Django 5.1.5 on 2025-08-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='entry_method',
            field=models.CharField(choices=[('online', 'オンライン'), ('manual', '手動入力')], default='online', max_length=10),
        ),
    ]
